### ISSUE TITLE
How to run

### ISSUE THREAD

**Issue by mzilot** [dot-build/telegram-js#2]
Hi,
How can i run and test this sample.js?
I'm using default node js and get error when run node sample.js or npm test.

**Comment by darlanalves** [comment]
Hi!

Follow the comments on `sample.js`. You need to get the latest schema.json file, generate an API key on Telegram servers and point to the right IP addresses to run it.

If you still have issues, paste the error message here please.

Cheers,
Darlan.

**Comment by mzilot** [comment]
Hi,
It seems telegram release  layer 28 json on it's site, But now clients are using layer 54 and upper.
Where can i find the latest schema.json?

**Comment by darlanalves** [comment]
It's available on Telegram documentation page:

https://core.telegram.org/schema

There's also a JSON version for it:

https://core.telegram.org/schema/json

**Comment by mzilot** [comment]
Are you sure it's the latest schema layer? 
[https://core.telegram.org/schema/json](url)

**Comment by darlanalves** [comment]
Not really :/

I see what you see there. It should be the latest, though.

**Comment by goodmind** [comment]
Hi, 

What you think about 
https://github.com/goodmind/telegram-tl-node and https://raw.githubusercontent.com/goodmind/telegram.link/master/lib/api-tlschema.json

/cc @darlanalves @mohammadrezaprw

**Comment by diego77777** [comment]
Hi, 
- i visited `my.telegram.org` and inserted in `sample.js` `APP_ID` and `APP_HASH` after creating them
- I downloaded `api-schema.json` from `https://core.telegram.org/schema/json`
- I did `sudo npm install`
- I `ran nodemon sample.js`

```
(function (exports, require, module, __filename, __dirname) { import { Telegram } from 'telegram-js';
                                                              ^^^^^^
SyntaxError: Unexpected token import
```
what I'm doing wrong?

**Comment by goodmind** [comment]
@diego77777 use `require` not `import`

```js
let { Telegram } = require('telegram-js');
```

**Comment by diego77777** [comment]
@goodmind thanks, i changed them with

```
let { Telegram } = require('telegram-js');
let MTProto = require('telegram-mt-node');
let TypeLanguage = require('telegram-tl-node');

let schema = ('./api-schema.json');
```

the result is

```
Error: Cannot find module 'telegram-js'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/diego/telegram-js-master/sample.js:1:82)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

I don't get it... o_O

**Comment by goodmind** [comment]
@diego77777 did you install module itself? `npm i telegram-js`

**Comment by goodmind** [comment]
@diego77777 also you forget `require` in `schema`

```js
let schema = require('./api-schema.json');
```

**Comment by diego77777** [comment]
sorry for the typo in schema -_-

I tried to install telegram-js before, but I get an ENOSELF error: refusing to install telegram-js as a dependency of itself.

I'm sure that it's my fault and I'm doing something wrong, but I don't know what...

**Comment by goodmind** [comment]
@diego77777 create folder in another place with **ONLY** sample.js

**Comment by pjuska01** [comment]
I am getting:
$ node sample

/usr/local/bin/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:137
            var typeName = type[1];
                               ^

TypeError: Cannot read property '1' of null
    at ConstructorBuilder.buildSerialize (/usr/local/bin/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:137:32)
    at ConstructorBuilder.build (/usr/local/bin/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:73:28)
    at new ConstructorBuilder (/usr/local/bin/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:46:24)
    at buildType (/usr/local/bin/node_modules/telegram-tl-node/lib/builder/type-builder.js:77:12)
    at buildTypes (/usr/local/bin/node_modules/telegram-tl-node/lib/builder/type-builder.js:51:38)
    at Telegram.useSchema (/usr/local/bin/node_modules/telegram-js/dist/telegram.js:336:13)
    at Object.<anonymous> (/usr/local/bin/sample/sample.js:21:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)

**Comment by goodmind** [comment]
@pjuska01  use https://github.com/zerobias/telegram-mtproto
