### ISSUE TITLE
Error: Cannot read property '1' of null

### ISSUE THREAD

**Issue by jeremy8883** [dot-build/telegram-js#5]
Hey, I'm having an issue getting the sample.js file working. I've converted the es6 modules to node requires, I've pulled the latest schema from [here](https://core.telegram.org/schema/json), am using the app id and hash from the dev console, and fixed the function typo on line 38. Unfortunately I'm getting the following:

```
/Users/jeremy/telegram/telegram-js/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:137
            var typeName = type[1];
                               ^

TypeError: Cannot read property '1' of null
    at ConstructorBuilder.buildSerialize (/Users/jeremy/telegram/telegram-js/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:137:32)
    at ConstructorBuilder.build (/Users/jeremy/telegram/telegram-js/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:73:28)
    at new ConstructorBuilder (/Users/jeremy/telegram/telegram-js/node_modules/telegram-tl-node/lib/builder/constructor-builder.js:46:24)
    at buildType (/Users/jeremy/telegram/telegram-js/node_modules/telegram-tl-node/lib/builder/type-builder.js:77:12)
    at buildTypes (/Users/jeremy/telegram/telegram-js/node_modules/telegram-tl-node/lib/builder/type-builder.js:51:38)
    at Telegram.useSchema (/Users/jeremy/telegram/telegram-js/dist/telegram.js:338:13)
    at Object.<anonymous> (/Users/jeremy/telegram/telegram-js/sample.js:16:10)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```

My node version is v6.10.0. Any possible ideas? Kind thanks

**Comment by nebaz** [comment]
check schema.js and replace "#" to "string" and  "flags.0?" to "string"

**Comment by jeremy8883** [comment]
Thanks! But I gave it a try and am still getting the same error.

**Comment by darlanalves** [comment]
I think is because TL introduced new syntax definitions, like dependant types, that weren't there a while ago. This is unlikely to be supported by `telegram-tl-node` engine.
It has to be implemented in the underlying libraries to make it available, but I wouldn't go that way. This library is rather old and poorly written.

Check this out:
https://github.com/enricostara/telegram-tl-node/issues/4
